/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const nbt_file_read: (a: number, b: number, c: number) => void;
export const nbt_file_read_lazy: (a: number, b: number, c: number, d: number) => void;
export const nbt_file_write: (a: number, b: number) => void;
export const nbt_file_dispose: (a: number) => void;
export const nbt_get_string: (a: number, b: number, c: number, d: number) => void;
export const nbt_get_number: (a: number, b: number, c: number, d: number) => void;
export const nbt_get_root: (a: number, b: number) => void;
export const nbt_tag_type: (a: number, b: number) => void;
export const nbt_tag_as_string: (a: number, b: number) => void;
export const nbt_tag_as_number: (a: number, b: number) => void;
export const nbt_tag_get_compound_keys: (a: number, b: number) => void;
export const nbt_tag_get_compound_value: (a: number, b: number, c: number, d: number) => void;
export const nbt_tag_get_list_length: (a: number, b: number) => void;
export const nbt_tag_get_list_item: (a: number, b: number, c: number) => void;
export const nbt_file_set_list_item_string: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => void;
export const nbt_tag_dispose: (a: number) => void;
export const nbt_tag_get_string: (a: number, b: number, c: number, d: number) => void;
export const nbt_tag_get_number: (a: number, b: number, c: number, d: number) => void;
export const nbt_tag_set_string: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const nbt_tag_set_number: (a: number, b: number, c: number, d: number, e: number) => void;
export const nbt_region_read: (a: number, b: number, c: number) => void;
export const nbt_region_write: (a: number, b: number) => void;
export const nbt_region_dispose: (a: number) => void;
export const __wbindgen_export_0: (a: number, b: number) => number;
export const __wbindgen_export_1: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_export_2: (a: number, b: number, c: number) => void;
